#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Business Area',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: '타생지연',   url: 'proj-1'}
- {name: 'Project Two',   url: 'proj-2'}
- {name: 'Project Three', url: 'proj-3'}
- {name: 'Project Four',  url: 'proj-4'}
- {name: 'Project Five',  url: 'proj-5'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/leechan0415'}
- {icon: 'youtube',  link: 'https://www.youtube.com/@leechan0415'}
- {icon: 'envelope',  link: 'mailto:lcy1152@naver.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'


#-------------------------------
# SEO Section

seo:
  description: '00MM(오오엠엠)은 숏폼 드라마, 행사·인터뷰 영상, SNS 콘텐츠를 제작하는 영상 크리에이티브 스튜디오입니다.'
  rel-author: ''
  rel-publisher: ''

#-------------------------------
# Google Analytics Section

google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

disqus:
  comments: false
  disqus_shortname: ''
